name: wavi_claras
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: ^1.0.0
  cupertino_icons: ^1.0.3
  freezed_annotation: ^0.14.2
  get: ^4.1.4
  get_storage: ^2.0.2
  intl: ^0.17.0
  json_serializable: ^4.1.3
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  freezed: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
